### ISSUE TITLE
Amazing EA

### ISSUE THREAD

**Issue by Cryptologycz** [Andrukas8/AR_Trading_Panel_For_MT5#1]
I'm really amazed but I believe thats it's missing a magic number  tht will add a big value and trail stop if not I'm not sure and you can add a hedge strategy would make it super robot

Al. The best

**Comment by Andrukas8** [comment]
Thanks! Basically, this whole EA is a big prototype. I'm adding all strategies I'm learning to it, to see if they work. Some of them prove to be unprofitable, but still stay in the code just in case for future use maybe.
It does have some SL trailing (based on a fractal, a fixed number of pips, a moving average, even based on some Ichimoku lines and based previous candle close. Let me know the rules for the SL trailing you would like to see in this EA, I'll try to implement those too.
Also, I don't quite understand the "magic number" feature. If you could explain it, I might find time to implement it too.
